version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          bash build_and_push.sh
