version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          docker build -t jixone/rust-ci:$CIRCLE_BRANCH .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push jixone/rust-ci:$CIRCLE_BRANCH
